[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan db:seed --force && php artisan storage:link && php-fpm8.3 -D && nginx -g 'daemon off;'"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
